#config_version=6
#test update
## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

modes:
  - attract
  - base
  
#displays:
#  window:
#    width: 800
#    height: 600

hardware:
  platform: fast
  #driverboards: fast
  
fast:
  net:
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208
        order: 1
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
        #breakouts:
         # - port: 1
          #  model: FP-PWR-0030
    port: auto
    baud: 921600
    debug: False
    
playfields:
  playfield:
    tags: default
    default_source_device: None  # use None in steps before 8

switches:
  s_flipper_left:
    number: 3208-27
    tags: left_flipper
  s_flipper_left_eos:
    number: 3208-5
  s_flipper_right:
    number: 3208-24
    tags: right_flipper
  s_flipper_right_eos:
    number: 3208-1
  s_sling_left:
    number: 3208-6
  s_sling_right:
    number: 3208-9
  s_plunger_lane:
    number: 3208-0
  s_launch_button:
    number: 3208-26
#!s_trough1:
#!  number: 1
#!s_trough2:
#!  number: 2
#!s_trough3:
#!  number: 3
#!s_trough4:
#!  number: 4
#!s_trough5:
#!  number: 5
#!s_trough6:
#!  number: 6
#!s_trough_jam:
#!  number: 7

coils:
  c_flipper_left_main:
    number: 3208-2
    allow_enable: true
  c_flipper_left_hold:
    number: 3208-3
    allow_enable: true
  c_flipper_right_main:
    number: 3208-4
    allow_enable: true
  c_flipper_right_hold:
    number: 3208-5
    allow_enable: true
  c_sling_left:
    number: 3208-6 
    default_pulse_ms: 15
  c_sling_right: 
    number: 3208-7
    default_pulse_ms: 15
#c_trough_eject     
  c_plunger:
    number: 3208-0
    default_pulse_ms: 20

autofire_coils:
  ac_slingshot_left:
    coil: c_sling_left
    switch: s_sling_left
  ac_slingshot_right:
    coil: c_sling_right
    switch: s_sling_right

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    enable_events: machine_reset_phase_3
    eos_switch: s_flipper_left_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right
    enable_events: machine_reset_phase_3
    eos_switch: s_flipper_right_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    
ball_devices:
#  bd_trough:
#    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
#    eject_coil: c_trough_eject
#    tags: trough, home, drain
#    jam_switch: s_trough_jam
#    eject_coil_jam_pulse: 15ms
#    debug: true
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    mechanical_eject: true
    player_controlled_eject_event: s_launch_button_active
