#config_version=6

#virtual_platform_start_active_switches:
#  - s_trough_1
#  - s_trough_2
#  - s_trough_3

switches:

# Trough Switches

  s_trough_1:
    number: 3208-0
    type: NC
  s_trough_2:
    number: 3208-1
    type: NO
  s_trough_3:
    number: 3208-2
    type: NO
  s_trough_4:
    number: 3208-3
    type: NO
  s_trough_5:
    number: 3208-4
    type: NO
  s_trough_6:
    number: 3208-5
    type: NO
  s_trough_jam:
    number: 3208-6
    type: NO

#Cabinet Switches

  s_plunger_lane:
    number: 3208-7

  s_flipper_right_eos:
    number: 3208-8

  s_sling_right:
    number: 3208-9

  s_outlane_right: #check this - not sure which switch it's for
    number: 3208-10
    tags: playfield_active

  s_inlane_1_right: #check this - not sure which switch it's for
    number: 3208-11
    tags: playfield_active

  s_inlane_2_right: #check this - not sure which switch it's for
    number: 3208-12
    tags: playfield_active

  s_flipper_left_eos:
    number: 3208-13

  s_inlane_left: #check this - not sure which switch it's for
    number: 3208-14
    tags: playfield_active

  s_outlane_left: #check this - not sure which switch it's for
    number: 3208-15
    tags: playfield_active

  s_sling_left:
    number: 3208-16

  s_flipper_right:
    number: 3208-24
    tags: right_flipper

  s_start_button:
    number: 3208-25
    tags: start

  s_launch_button:
    number: 3208-26

  s_flipper_left:
    number: 3208-27
    tags: left_flipper