#config_version=6

ball_devices:

  bd_plunger:
    ball_switches: s_plunger_lane
    player_controlled_eject_event: s_launch_button_active
    mechanical_eject: true
    eject_coil: c_plunger
    eject_timeouts: 5s
    #confirm_eject_type: switch #I don't have this yet
    #confirm_eject_switch: s_plunger_lane_exit #I don't have this yet
    
#  bd_trough:
#    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5, s_trough_6, s_trough_jam
#    eject_coil: c_trough_eject #this is how the ball gets out of the trough
#    eject_targets: bd_plunger #when ball is ejected from trough it goes to plunger before playfield
#    tags: trough, home, drain

    #TAGS
    #trough is default place where balls live. Could also be lock, newton ball
    #home is ok place where balls can be when ball starts
    #drain means that when a ball comes here it has drained from play

    #jam_switch: s_trough_jam
    #eject_coil_jam_pulse: 15ms
    #debug: false
