#config_version=6

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml
  
modes:
  - attract
  - base
  
#displays:
#  window:
#    width: 800
#    height: 600

hardware:
  platform: fast
  driverboards: fast
  
fast:
  net:
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208
        order: 1
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
        #breakouts:
         # - port: 1
          #  model: FP-PWR-0030
    port: auto
    baud: 921600
    debug: False
    
playfields:
  playfield:
    default_source_device: bd_trough # this is the default location ball device
    tags: default

autofire_coils:
  ac_slingshot_left:
    coil: c_sling_left
    switch: s_sling_left
  ac_slingshot_right:
    coil: c_sling_right
    switch: s_sling_right
    
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    enable_events: machine_reset_phase_3
    #enable_events: machine_reset_phase_3 allows flipper coils to work during attract
    eos_switch: s_flipper_left_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right
    enable_events: machine_reset_phase_3
    #enable_events: machine_reset_phase_3 allows flipper coils to work during attract
    eos_switch: s_flipper_right_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    
