#config_version=6
#yaml doesn't allow tabs - make sure to use spaces
#Make sure that all the "child" elements are indented the same, so s_left_flipper and s_right_flipper both need to be indented the same
#Make sure you do not have a space before each colon.
#Make sure you do have a space after each colon.
#Make sure you have the #config_version=6 as the first line in your file.
#https://missionpinball.org/latest/troubleshooting/debugging_yaml_parse_errors/

#mpf -x or -X is for running without physical hardware

#config section imports various other config files
config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml

#modes section imports various Godot modes  
modes:
  - attract
  - base
  
#displays:
#  window:
#    width: 800
#    height: 600

#hardware section is for referencing FAST boards or virtual switches
hardware:
  platform: fast
  driverboards: fast
  
#FAST code
fast:
  net:
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208
        order: 1
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
        #breakouts:
         # - port: 1
          #  model: FP-PWR-0030
    port: auto
    baud: 921600
    debug: False

#playfields section for adding main playfield, upper playfield    
playfields:
  playfield:
    default_source_device: bd_plunger #usually bd_trough # this is the default location ball device
    tags: default

#added from Demolition Man demo    
game:
  balls_per_game: 3
  max_players: 4

#added from Demolition Man demo
machine:
  balls_installed: 1
  min_balls: 1

#added from Demolition Man demo    
widget_styles:
  text_default:
    font_name: COOPBL
    font_size: 60
    adjust_top: 2
    adjust_bottom: 3
  space_title_huge:
    font_name: COOPBL
    font_size: 80
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space_title:
    font_name: COOPBL
    font_size: 70
    antialias: true
    adjust_top: 2
    adjust_bottom: 3

#  medium:
#    font_name: pixelmix
#    font_size: 8
#    adjust_top: 1
#    adjust_bottom: 1
#  small:
#    font_name: smallest_pixel-7
#    font_size: 9
#    adjust_top: 2
#    adjust_bottom: 3
#  tall_title:
#    font_name: big_noodle_titling
#    font_size: 20

autofire_coils:
  ac_slingshot_left:
    coil: c_sling_left
    switch: s_sling_left
  ac_slingshot_right:
    coil: c_sling_right
    switch: s_sling_right
    
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    #enable_events: machine_reset_phase_3 #enable_events: machine_reset_phase_3 allows flipper coils to work during attract
    eos_switch: s_flipper_left_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right
    #enable_events: machine_reset_phase_3 #enable_events: machine_reset_phase_3 allows flipper coils to work during attract
    eos_switch: s_flipper_right_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    
